spring:
  profiles:
    active: dev
  application:
    name: demo-spring-gateway

server:
  port: 12388

eureka:
  client:
    serviceUrl:
      defaultZone: http://${demo.spring.client.serviceUrl}:${demo.spring.client.port}/eureka
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      zone: ${spring.application.name}
      demo: ${spring.application.name}
    lease-renewal-interval-in-seconds: ${demo.spring.client.instance.renewalInterval}
    lease-expiration-duration-in-seconds: ${demo.spring.client.instance.expirationDuration}
zuul:
  host:
    max-per-route-connections: ${demo.spring.client.zuul.route.connections}
    max-total-connections: ${demo.spring.client.zuul.total.connections}
  routes: # 网关路由配置
    demo-spring-client-one: demo/one/**
    demo-spring-client-two: demo/two/**


