demo:
  spring:
    client:
      serviceUrl: 10.10.11.189
      port: 12380
      instance:
        renewalInterval: 15
        expirationDuration: 30
      zuul:
        route:
          connections: 100
        total:
          connections: 100